{
	"version": 1592500469,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/sprite27-sheet0.png",
		"images/marca-sheet0.png",
		"images/sprite55-sheet0.png",
		"images/fonte_bola.png",
		"images/sprite85-sheet0.png",
		"images/explosao1-sheet0.png",
		"images/explosao1-sheet1.png",
		"images/explosao1-sheet2.png",
		"images/sprite83-sheet0.png",
		"images/sprite79-sheet0.png",
		"images/sprite80-sheet0.png",
		"images/sprite76-sheet0.png",
		"images/sprite78-sheet0.png",
		"images/sprite81-sheet0.png",
		"images/sprite77-sheet0.png",
		"images/sprite84-sheet0.png",
		"images/particles3.png",
		"images/sprite86-sheet0.png",
		"images/sprite87-sheet0.png",
		"images/particles.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite2-sheet1.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"media/explosion bang 04.ogg",
		"media/epicwin1.ogg",
		"media/success pickup collect chime 01.ogg",
		"media/preview-space-epic.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"SweetAlert.css",
		"SweetAlert.js"
	]
}